/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_wpi_first_wpiutil_WPIUtilJNI */

#ifndef _Included_edu_wpi_first_wpiutil_WPIUtilJNI
#define _Included_edu_wpi_first_wpiutil_WPIUtilJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_wpi_first_wpiutil_WPIUtilJNI
 * Method:    now
 * Signature: ()J
 */


extern "C" jlong
Java_com_roboknights4348_lib_wpiutil_src_main_java_edu_wpi_first_wpiutil_WPIUtilJNI_now(JNIEnv *env,
                                                                                        jclass clazz);
/*
 * Class:     edu_wpi_first_wpiutil_WPIUtilJNI
 * Method:    addPortForwarder
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_roboknights4348_lib_wpiutil_src_main_java_edu_wpi_first_wpiutil_WPIUtilJNI_addPortForwarder
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     edu_wpi_first_wpiutil_WPIUtilJNI
 * Method:    removePortForwarder
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_roboknights4348_lib_wpiutil_src_main_java_edu_wpi_first_wpiutil_WPIUtilJNI_removePortForwarder
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
