/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI */

#ifndef _Included_com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI
#define _Included_com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI
 * Method:    discreteAlgebraicRiccatiEquation
 * Signature: ([D[D[D[DII[D)V
 */
JNIEXPORT void JNICALL Java_com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI_discreteAlgebraicRiccatiEquation
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray);

/*
 * Class:     com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI
 * Method:    exp
 * Signature: ([DI[D)V
 */
JNIEXPORT void JNICALL Java_com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI_exp
  (JNIEnv *, jclass, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI
 * Method:    pow
 * Signature: ([DID[D)V
 */
JNIEXPORT void JNICALL Java_com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI_pow
  (JNIEnv *, jclass, jdoubleArray, jint, jdouble, jdoubleArray);

/*
 * Class:     com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI
 * Method:    isStabilizable
 * Signature: (II[D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_roboknights4348_lib_wpimath_src_main_java_edu_wpi_first_math_WPIMathJNI_isStabilizable
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
